var car = 'subaru';
console.log("Is car == 'subaru'? I predict true.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict false.");
console.log(car == 'honda');
console.log("Is car != 'toyota'? I predict true.");
console.log(car != 'toyota');
console.log("Is car != 'subaru'? I predict false.");
console.log(car != 'subaru');
console.log("Is car === 'subaru'? I predict true.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict false.");
console.log(car === 'Subaru');
console.log("Is car !== 'honda'? I predict true.");
console.log(car !== 'honda');
console.log("Is car !== 'subaru'? I predict false.");
console.log(car !== 'subaru');
console.log("Is car > 'honda'? I predict true.");
console.log(car > 'honda');
console.log("Is car < 'toyota'? I predict true.");
console.log(car < 'toyota');
